version: "0.1"

services:
    fastapi-image-processing:
        build: .
        ports:
        - "8001:8001"
        volumes:
        - .:/code
        environment:
        - PYTHONUNBUFFERED=1
        - FASTAPI_ENV=development
        - FASTAPI_HOST=